# Site settings
title: Tim Griffith
email: tmgriffith1991@gmail.com
url: https://tmgriffith.github.io
description: "This is the portfolio website of Timothy Griffith, where he displays all his current and past projects. Tim is a Full Stack JavaScript Developer who specializes in web development."
skills: "Front End Web Developer"
meta_author: Griffith Tim
favicon: /favicon.ico

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7B633F #80B3FF
  primary-rgb: "123, 99, 63" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Tim Griffith
  location: Location
  social:
  credits: Credits
  hire-me: I do freelance and contract work! Send me a message with the form above

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url: https://www.facebook.com/timmygndamornin
  - title: linkedin
    url: https://www.linkedin.com/in/timothy-griffith-252ba6b2
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/tmgriffith

# Postal address (add as many lines as necessary)
address:
  - line: 4371 Illinois St
  - line: San Diego, CA 92104

# Credits content
credits: 'The theme used for this site was modified from a free theme on <a href="http://startbootstrap.com">Start Bootstrap</a> called Freelancer.'

# Build settings
markdown: kramdown
permalink: pretty
